### ISSUE TITLE
Missing string.h in ft_strlcpy main

### ISSUE THREAD

**Issue by bpisano** [jtoty/Libftest#2]
Can't compile my ft_strlcpy.c because string.h is missing in your main.

> = Additional_functions =========================================================
> 
> = ft_strlcpy.c =================================================================
> $> norminette ft_strlcpy.c | grep -E '(Error|Warning)'
> $> clang -Wextra -Wall -Werror ft_strlcpy.c main.c libft.a -o user_exe
> 
> /Users/bpisano/cursus/Libftest/tests/Additional_functions/ft_strlcpy/main.c:36:2: error: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Werror,-Wimplicit-function-declaration]
>         memset(dest, 0, 15);
>         ^
> /Users/bpisano/cursus/Libftest/tests/Additional_functions/ft_strlcpy/main.c:36:2: note: include the header <string.h> or explicitly provide a declaration for 'memset'
> 1 error generated.
>

**Comment by jtoty** [comment]
Fixed, thank you for the issue.
