### ISSUE TITLE
Wrong ft_itoa_base tests

### ISSUE THREAD

**Issue by bpisano** [jtoty/Libftest#3]
Tests on ft_itoa_base seems to be broken. I've got an ft_itoa.c that simply make a call on ft_itoa_base with the 10 base and works perfectly with your tests.
Here's my ft_itoa_base code :
```
#include "libft.h"

char	*ft_itoa_base(int n, int base)
{
	char	*nbr;
	char	*s_base;

	s_base = "0123456789ABCDEF";
	if (n == -2147483648)
		nbr = ft_strjoin("-", ft_strjoin(ft_itoa_base(-(n / base), base),
						ft_itoa_base(8, base)));
	else if (n < 0)
		nbr = ft_strjoin("-", ft_itoa_base(-n, base));
	else
		nbr = n < base ? ft_strdup(ft_strsub(s_base, n % base, 1)) :
						ft_strjoin(ft_itoa_base(n / base, base),
						ft_strsub(s_base, n % base, 1));
	return (nbr);
}
```
```
#include "libft.h"

char	*ft_itoa(int n)
{
	return (ft_itoa_base(n, 10));
}
```
<img width="575" alt="screen shot 2017-11-14 at 20 52 16" src="https://user-images.githubusercontent.com/16155946/32801630-e70ee7ba-c97d-11e7-8455-9ba8022b45aa.png">

**Comment by jtoty** [comment]
Tests are made like on exam, i.e only base 10 should handle '-' sign, with others bases minus sign for negative numbers is simply ignored. That's why you pass only base 10 test.
