### ISSUE TITLE
[ft_lstmap] compilation issue stemming from main.c

### ISSUE THREAD

**Issue by benkimbuilds** [jtoty/Libftest#35]
ft_lstmap testing file (main.c line 150) invokes:
`ft_lstmap(elem, (void *)&ft_mapelem, (void *)&ft_mapdelelem)`
when ft_lstmap only takes two arguments in its function signature.

**Comment by jtoty** [comment]
According to the actual subject of libft, ft_lstmap takes three arguments:

Prototype: `t_list *ft_lstmap(t_list *lst, void *(*f)(void *), void (*del)(void *));`

However, ft_lstmap of the old subject took only two arguments. You can test it on the [old-libft branch](https://github.com/jtoty/Libftest/tree/old-libft)

**Comment by benkimbuilds** [comment]
Any chance you could share the subject on your end? I received a 'new' one
[here](https://github.com/jtoty/Libftest/files/4049607/ft_libft_new.pdf) that contradicts your statement.

**Comment by jtoty** [comment]
It seems that subjects are different. [Here ](https://www.dropbox.com/s/y93fzq4jv91ikgk/libft_subject.pdf?dl=0)the one I have.

**Comment by benkimbuilds** [comment]
Yes, it is different for the last problem. Merci
