### ISSUE TITLE
Minor [-Wpointer-compare] error in ft_split main.c

### ISSUE THREAD

**Issue by amalliar** [jtoty/Libftest#36]
/home/amalliar/Desktop/Libftest/tests/Part2_functions/ft_split/main.c:32:22: error: comparing a pointer to a null character constant; did you mean to compare to NULL? [-Werror,-Wpointer-compare]
        while (tabstr[i] != '\0')
                            ^~~~
                            (void *)0

**Comment by jtoty** [comment]
Thank you for the issue, I fixed this mistake :)
