### ISSUE TITLE
ft_lstadd_back segmentation fault

### ISSUE THREAD

**Issue by kigzz** [jtoty/Libftest#39]
Hello, 

First of all, thanks for you bash script, it's really helpful.

I got an issue with this function

![Screenshot from 2020-07-22 15-15-00](https://user-images.githubusercontent.com/60890009/88180770-289a8a80-cc2e-11ea-9f12-d6eb8a31ac7f.png)

When I'm testing this function with this little programs, I got the expected results
![Screenshot from 2020-07-22 15-20-48](https://user-images.githubusercontent.com/60890009/88181314-f76e8a00-cc2e-11ea-8764-3980ce0e9012.png)
![Screenshot from 2020-07-22 15-20-31](https://user-images.githubusercontent.com/60890009/88181330-fb021100-cc2e-11ea-9fbd-f9d28671afbb.png)

Idk if the problem is coming from my implementation or the test program.

Thank you for your help

**Comment by jtoty** [comment]
Hello,

I think your implementation is not correct.
It works for the cases tested in your main, but it does not cover all the cases

**Comment by kigzz** [comment]
You are right. I just needed to add 2 conditions. 

`If (*new != NULL) {`
        `if` ((*alst) != NULL)``
              Do your things``
       ` else`
              `*alst = new }`
