### ISSUE TITLE
Libftest doesn't locate my functions

### ISSUE THREAD

**Issue by miguelm9** [jtoty/Libftest#40]
First of all, thanks for the awesome tool.

My issue is that, when trying to run the test, none of my functions are located. I am sure the path I've specified in the config file is correct because it DOES find my header file and my makefile. So I don't know what the issue can be. 

This is what appears after I run the test:

![image](https://user-images.githubusercontent.com/39597568/89678630-d1fca400-d8ef-11ea-9879-39c2462d1137.png)

A little help is much appreciated.

Thanks in advance!

**Comment by jtoty** [comment]
Hello !
It could happen when your source files are missing from Makefile or if the function name is not the same as expected.
I tried with your libft on your github and I could run the tests (cf screenshot)
![image](https://user-images.githubusercontent.com/20699907/89714164-1abe6680-d99d-11ea-9587-4818c973a235.png)
Let me know if it helped you.

**Comment by miguelm9** [comment]
Yup, I updated the Makefile, but I don't get the same thing you do. Now I get this:
![image](https://user-images.githubusercontent.com/39597568/89714350-265e5d00-d99e-11ea-80c8-7c34df2df591.png)

Why do I get the compilation error?

**Comment by jtoty** [comment]
You should check compilation error message to understand what is the problem, without that it's hard to guess what happened

**Comment by miguelm9** [comment]
Oh my God, it wasn't able to find the 'clang' command because I didn't install it on my machine. My bad. 

Thanks a lot for the awesome tool and for the quick response!
