### ISSUE TITLE
copied Applications

### ISSUE THREAD

**Issue by AleksanderIrbe** [jtoty/Libftest#44]
Пользовался Libftest три недели. Вчера при загрузке из репозитория программа начала вести себя странно, надолго задумывалась. Сегодня было чем-то занято все пространство в памяти. Оказалось, после запуска начинает в свой temp копировать все приложения из Applications. После того, как поставил копию, сохраненную на флешке, это прекратилось. Предполагаю, что если это не вирус, и не какая-то ошибка на моем компьютере, то может быть неудачная модификация программы.

**Comment by jtoty** [comment]
I don't understand your language, could you write in english please ?
