### ISSUE TITLE
ft_memchr compil failed

### ISSUE THREAD

**Issue by ninofaivre** [jtoty/Libftest#45]
the compil of ft_memchr was failing because U was trying to printf a void argument to the test n°6 :

else if (arg == 6)
{
	int tab[7] = {-49, 49, 1, -1, 0, -2, 2};

	printf("%s", ft_memchr(tab, -1, 7));
}
ft_memchr return a void argument and if U try to printf it will compil failed because of clang flags (-Werror -Wall -Wextra).

For get it works I just did this change :

else if (arg == 6)
{
	int tab[7] = {-49, 49, 1, -1, 0, -2, 2};

	printf("%s", (char *)ft_memchr(tab, -1, 7));
}
and now their is no longer error with clang flags and it compil. So now I can test my ft_memchr.

I apologize for my bad English and my bad utilization of github. Mb I should did a pull request or something like this but I'm new in the world of programing and in 42 (I'm in 42 Paris).

I think this error is not on every config but some of my teammate had the same error than me and all was just like ok, this test doesn't works and just ignore it. For information I'm on linux manjaro.

**Comment by jtoty** [comment]
I added the cast, thank you for the issue :+1:
