### ISSUE TITLE
False error in ft_strmapi test if iteration is implemented from end to start

### ISSUE THREAD

**Issue by colorific** [jtoty/Libftest#5]
Expected:
012345678910$
lOrEm IpSuM%

User output:
109876543210$
lOrEm IpSuM%
```
len = ft_strlen(s);
if((res = (char *)malloc(len + 1)))
{
	res[len] = s[len];
	while (len--)
		res[len] = f(len, s[len]);
}
```

That's because of `ft_print_result2(i)` is invoked in `mapi` function for each index.
But there is no words in the Subject that the iteration should be done from 0 to end.

**Comment by jtoty** [comment]
Fixed, thank you for the issue.
